services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    depends_on:
      - redis

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  simpleweb:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 5001:5000
    depends_on:
      - redis

volumes:
  redis:
  postgres:
  pgadmin:
