services:
  redis:
    restart: unless-stopped
    image: redis
    ports:
      - 6379:6379
    networks:
      - worker
    volumes:
      - redis:/data

  worker:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - redis
    networks:
      - worker
      - server-redis

volumes:
  redis:

networks:
  server-redis:
    external: true
  worker:
    external: false
